Add option to connect to testnet and download db
Cardinal-Cryptography/Aleph-Testnet pull request #35
Opened 2022-07-15 10:51 UTC by maciejnems

This PR is part of work on connecting 100 nodes to testnet. It introduces option to connect to testnet using our Aleph-Testnet repo. Way it is done is just passing `chain='testnet'` to either `setup_nodes` or `setup_benchmark`. The script depending on 
* bootnodes argument will pass hardcoded bootnodes for testnet or provided ones
* sync_from_genesis will sync from block 0 or download testnet db

2022-07-15 11:11 UTC, timorl approved these changes

2022-07-19 09:50 UTC, fixxxedpoint requested changes
LGTM. Left a request regarding possible re-download. In general, we try to keep these scripts foolproof and try to make them support mutliple re-executions.

2022-07-19 15:19 UTC, maciejnems commented on fabfile.py
> +            f'tar xvzf db.tar.gz -C data/{auth}/chains/testnet; '\
I added set -e at the begining

2022-07-19 15:49 UTC, fixxxedpoint approved these changes
LGTM

2022-07-19 16:52 UTC, merged